#!/usr/bin/env bash

BASEDIR=$(dirname $(realpath $0))
cd "$BASEDIR"

TAG="$(curl -sI https://github.com/P3TERX/GeoLite.mmdb/releases/latest | grep location: | cut -d / -f 8 | tr -d '\r' )"
echo $TAG

# download GeoLite2 databases
mkdir -p ~/.mmdb/$TAG
pushd ~/.mmdb/$TAG
for file in GeoLite2-{ASN,City,Country}.mmdb; do
	ln -svf $TAG/$file ../$file
	[[ -f $file ]] && continue
	curl -#L https://github.com/P3TERX/GeoLite.mmdb/releases/download/$TAG/$file > $file
done
popd

# download mmdbinspect
# export GOBIN=$PWD
# [[ -f mmdbinspect ]] || go install github.com/maxmind/mmdbinspect/cmd/mmdbinspect@main
[[ -f mmdbinspect ]] || {
	go mod tidy
	go build -v -o mmdbinspect .
}
