#!/usr/bin/env bash

BASEDIR=$(dirname $(realpath $0))
cd "$BASEDIR"

TAG=2024.03.13

# download mmdbinspect
export GOBIN=$PWD
[[ -f mmdbinspect ]] || go install github.com/maxmind/mmdbinspect/cmd/mmdbinspect@main

# download GeoLite2 databases
mkdir -p $TAG
pushd $TAG
for file in GeoLite2-{ASN,City,Country}.mmdb; do
	ln -svf $TAG/$file ../$file
	[[ -f $file ]] && continue
	wget https://github.com/P3TERX/GeoLite.mmdb/releases/download/$TAG/$file
done
popd
