#!/usr/bin/env bash

set -u

BASEDIR=$(dirname $(realpath $0))
cd "$BASEDIR"

./mmdbinspect \
	-db ~/.mmdb/GeoLite2-ASN.mmdb \
	-db ~/.mmdb/GeoLite2-City.mmdb \
	-db ~/.mmdb/GeoLite2-Country.mmdb \
	${1}
